---
name: Update and Build Nautobot Lab Container

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * *"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  HUB_URL: "https://hub.docker.com/v2/repositories/networktocode/nautobot-lab"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest Nautobot release
        id: get_nautobot_release
        run: |
          latest_release=$(curl -s \
            https://api.github.com/repos/nautobot/nautobot/releases/latest \
            | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "::set-output name=version::$latest_release"

      - name: Get Nautobot Lab image tag
        id: get_nautobot_lab_tag
        run: |
          tags=$(curl -s "$HUB_URL/tags/")
          latest_digest=$(curl -s "$HUB_URL/tags/" \
            | jq -r '.results[] | select(.name == "latest") | .images[0].digest')

          for row in $(echo $tags | jq -r '.results[] | @base64'); do
            tag=$(echo $row | base64 --decode | jq -r '.name')
            digest=$(echo $row | base64 --decode | jq -r '.digest')

            if [ "$tag" == "latest" ]; then
              continue
            elif [ "$digest" == "$latest_digest" ]; then
              echo "::set-output name=tag::$tag"
              break
            fi
          done

      - name: Compare versions and set environment variable
        id: compare_versions
        run: |
          nautobot_version="${{ steps.get_nautobot_release.outputs.version }}"
          nautobot_lab_tag="${{ steps.check_nautobot_lab_tag.outputs.tag }}"

          if [[ "$nautobot_version" == "$nautobot_lab_tag" ]]; then
            echo "Nautobot and Nautobot Lab versions match."
            exit 0
          else
            echo "NAUTOBOT_VERSION=$nautobot_version" >> "$GITHUB_ENV"
          fi

      - name: Build and push Nautobot Lab images
        env:
          NAUTOBOT_VERSION: ${{ env.NAUTOBOT_VERSION }}
        run: |
          if [[ -z "${NAUTOBOT_VERSION}" ]]; then
            echo "Nautobot Lab is up to date."
            exit 0
          else
            docker build -t networktocode/nautobot-lab:${NAUTOBOT_VERSION} .
            docker build -t networktocode/nautobot-lab:latest .
            echo $DOCKERHUB_TOKEN \
              | docker login \
                --username $DOCKERHUB_USERNAME \
                --password-stdin
            docker push networktocode/nautobot-lab:${NAUTOBOT_VERSION}
            docker push networktocode/nautobot-lab:latest
          fi
