---
name: "CI"
on: # yamllint disable
  push:
    branches:
      - "main"
  pull_request:
  release:
    types: [published]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "CHECKOUT REPOSITORY CODE"
        uses: "actions/checkout@v2"
      - name: "SETUP ENVIRONMENT"
        uses: "networktocode/gh-action-setup-poetry-environment@v4"
      - name: "RUN YAMLLINT ON ANSIBLE PLAYBOOK"
        run: "poetry run yamllint ."
      - name: "RUN HADOLINT ON DOCKERFILE"
        uses: "hadolint/hadolint-action@v3.1.0"
        with:
          dockerfile: Dockerfile
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "CHECKOUT REPOSITORY CODE"
        uses: "actions/checkout@v2"
      - name: "BUILD NAUTOBOT-LAB CONTAINER"
        run: "docker build -t networktocode/nautobot-lab:latest ."
      - name: "START NAUTOBOT-LAB CONTAINER"
        run: "docker run -itd --name nautobot networktocode/nautobot-lab:latest"
      - name: "PAUSE TO ALLOW THE CONTAINER TO BOOT"
        run: "sleep 30"
      - name: "TEST NAUTOBOT-LAB CONTAINER"
        run: "docker exec -t nautobot pytest ./templates/tests/tests.py"
